services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: next-frontend
        ports:
            - 3000:3000
        environment:
            - PORT=3000
            - NEXT_PUBLIC_API_URL=http://localhost:9921
        networks:
            - clinic-network
networks:
    clinic-network:
        driver: bridge