services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: next-frontend
        ports:
            - '${PORT}:3000'
        volumes:
            - ./docker-data-frontend:/app
        environment:
            - PORT=3000
            - NEXT_PUBLIC_API_URL=http://localhost:9921